paths:
  silver_base: "datamart/silver"
  gold_base: "datamart/gold"
  config: "config/gold_config.yaml"

static_features:
  attributes:
    - Age
    - Age_valid
    - Occupation
  financials:
    - Annual_Income
    - Monthly_Inhand_Salary
    - Num_Bank_Accounts
    - Num_Credit_Card
    - Interest_Rate
    - Num_of_Loan
    - Type_of_Loan_list
    - Delay_from_due_date
    - Num_of_Delayed_Payment
    - Changed_Credit_Limit
    - Num_Credit_Inquiries
    - Credit_Mix
    - Outstanding_Debt
    - Credit_Utilization_Ratio
    - Credit_History_Age_Months
    - Payment_of_Min_Amount
    - Amount_invested_monthly
    - Payment_Behaviour
    - Monthly_Balance

clickstream_features:
  - fe_1
  - fe_2
  - fe_3
  - fe_4
  - fe_5
  - fe_6
  - fe_7
  - fe_8
  - fe_9
  - fe_10
  - fe_11
  - fe_12
  - fe_13
  - fe_14
  - fe_15
  - fe_16
  - fe_17
  - fe_18
  - fe_19
  - fe_20

loan_types:
  expected:
    - Auto Loan
    - Credit-Builder Loan
    - Debt Consolidation Loan
    - Home Equity Loan
    - Mortgage Loan
    - Not Specified
    - Payday Loan
    - Personal Loan
    - Student Loan
  default: No_Loan